
/**************************************************************
 *	
 *	BossBattleSongLooping, 8 bit, 11025Hz,
 *	1 channel, 725763 bytes/channel
 *	Total Size: 1 * 725763 + 4 (header) = 725807 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\hmdab\OneDrive\Documents\Senior Year\Fall 2019\CS2261\M04\BossBattleSongLooping.wav
 *	Time-stamp: Thu Dec 05 19:42:48 2019
 *	
 **************************************************************/

#ifndef __BOSSBATTLESONGLOOPINGH__
#define __BOSSBATTLESONGLOOPINGH__

#define BOSSBATTLESONGLOOPINGFREQ 11025
#define BOSSBATTLESONGLOOPINGLEN 725763

extern const unsigned char BossBattleSongLooping[725763];

#endif /* __BOSSBATTLESONGLOOPINGH__ */
