
/**************************************************************
 *	
 *	EnemyInjured, 8 bit, 11025Hz,
 *	1 channel, 21004 bytes/channel
 *	Total Size: 1 * 21004 + 4 (header) = 21048 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\hmdab\OneDrive\Documents\Senior Year\Fall 2019\CS2261\M04\EnemyInjured.wav
 *	Time-stamp: Thu Dec 05 19:30:38 2019
 *	
 **************************************************************/

#ifndef __ENEMYINJUREDH__
#define __ENEMYINJUREDH__

#define ENEMYINJUREDFREQ 11025
#define ENEMYINJUREDLEN 21004

extern const unsigned char EnemyInjured[21004];

#endif /* __ENEMYINJUREDH__ */
