
/**************************************************************
 *	
 *	GameSongLooping, 8 bit, 11025Hz,
 *	1 channel, 529920 bytes/channel
 *	Total Size: 1 * 529920 + 4 (header) = 529964 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\hmdab\OneDrive\Documents\Senior Year\Fall 2019\CS2261\M04\GameSongLooping.wav
 *	Time-stamp: Tue Nov 26 14:04:20 2019
 *	
 **************************************************************/

#ifndef __GAMESONGLOOPINGH__
#define __GAMESONGLOOPINGH__

#define GAMESONGLOOPINGFREQ 11025
#define GAMESONGLOOPINGLEN 529920

extern const unsigned char GameSongLooping[529920];

#endif /* __GAMESONGLOOPINGH__ */
