
/**************************************************************
 *	
 *	GameSongLooping, 8 bit, 11025Hz,
 *	1 channel, 1114106 bytes/channel
 *	Total Size: 1 * 1114106 + 4 (header) = 1114150 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\hmdab\OneDrive\Documents\Senior Year\Fall 2019\CS2261\M04\GameSongLooping.wav
 *	Time-stamp: Thu Dec 05 18:05:23 2019
 *	
 **************************************************************/

#ifndef __GAMESONGLOOPINGH__
#define __GAMESONGLOOPINGH__

#define GAMESONGLOOPINGFREQ 11025
#define GAMESONGLOOPINGLEN 1114106

extern const unsigned char GameSongLooping[1114106];

#endif /* __GAMESONGLOOPINGH__ */
