
/**************************************************************
 *	
 *	GemCollectSound, 8 bit, 11025Hz,
 *	1 channel, 4008 bytes/channel
 *	Total Size: 1 * 4008 + 4 (header) = 4052 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\hmdab\OneDrive\Documents\Senior Year\Fall 2019\CS2261\M04\GemCollectSound.wav
 *	Time-stamp: Tue Nov 26 14:46:13 2019
 *	
 **************************************************************/

#ifndef __GEMCOLLECTSOUNDH__
#define __GEMCOLLECTSOUNDH__

#define GEMCOLLECTSOUNDFREQ 11025
#define GEMCOLLECTSOUNDLEN 4008

extern const unsigned char GemCollectSound[4008];

#endif /* __GEMCOLLECTSOUNDH__ */
