
/**************************************************************
 *	
 *	HurtSound, 8 bit, 11025Hz,
 *	1 channel, 1402 bytes/channel
 *	Total Size: 1 * 1402 + 4 (header) = 1446 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\hmdab\OneDrive\Documents\Senior Year\Fall 2019\CS2261\M04\HurtSound.wav
 *	Time-stamp: Tue Nov 26 15:33:01 2019
 *	
 **************************************************************/

#ifndef __HURTSOUNDH__
#define __HURTSOUNDH__

#define HURTSOUNDFREQ 11025
#define HURTSOUNDLEN 1402

extern const unsigned char HurtSound[1402];

#endif /* __HURTSOUNDH__ */
