
/**************************************************************
 *	
 *	StartSoundLooping, 8 bit, 11025Hz,
 *	1 channel, 387175 bytes/channel
 *	Total Size: 1 * 387175 + 4 (header) = 387219 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\hmdab\OneDrive\Documents\Senior Year\Fall 2019\CS2261\M04\StartSoundLooping.wav
 *	Time-stamp: Tue Nov 26 14:25:24 2019
 *	
 **************************************************************/

#ifndef __STARTSOUNDLOOPINGH__
#define __STARTSOUNDLOOPINGH__

#define STARTSOUNDLOOPINGFREQ 11025
#define STARTSOUNDLOOPINGLEN 387175

extern const unsigned char StartSoundLooping[387175];

#endif /* __STARTSOUNDLOOPINGH__ */
