
/**************************************************************
 *	
 *	StartSoundLooping, 8 bit, 11025Hz,
 *	1 channel, 977472 bytes/channel
 *	Total Size: 1 * 977472 + 4 (header) = 977516 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\hmdab\OneDrive\Documents\Senior Year\Fall 2019\CS2261\M04\StartSoundLooping.wav
 *	Time-stamp: Thu Dec 05 19:40:32 2019
 *	
 **************************************************************/

#ifndef __STARTSOUNDLOOPINGH__
#define __STARTSOUNDLOOPINGH__

#define STARTSOUNDLOOPINGFREQ 11025
#define STARTSOUNDLOOPINGLEN 977472

extern const unsigned char StartSoundLooping[977472];

#endif /* __STARTSOUNDLOOPINGH__ */
